### ISSUE TITLE
Release under an open source license?

### ISSUE THREAD

**Issue by dhimmel** [tylerhall/photoz#1]
The blot post [Merging and Deduplicating a Whole Lot of Google Photos](https://tyler.io/merge-deduplicate-google-photos/) came up in my Google Discover feed. This project looks useful, and I envision using it someday, perhaps in a year or two.

I'd like to see photoz to continue to exist and be improved, either by @tylerhall or others. To that end, would it be possible to release the code under an open source license? I think this would go a long way to remove legal barriers to ensuring this codebase has an enduring legacy.

**Comment by tylerhall** [comment]
Thanks for pointing that out, @dhimmel. I've added an MIT license to the repo.
